#!/usr/bin/perl -w
# rename - Larry's filename fixer (+ -n dry-run)
# Usage: rename [options and exprs ...] -- [files ...]
# If no files are given, reads newline-separated filenames from STDIN.
use File::Find ();

my $allow_hidden  = 0;
my $allow_dash    = 0;
my $allow_ext     = 0;
my $preserve_ext  = 0;
my $dryrun        = 0;
my $recursive     = 0;
my $ignore_type   = '';
my @raw_argv      = @ARGV;

sub usage {
    return "Usage: rename [-n] [--recursive] [--type f|d] [--allow-hidden] [--allow-dash] [--allow-ext | --preserve-ext] expr [expr ...] [-- files ...]\n";
}

sub parse_option {
    my ($args_ref, $index_ref) = @_;
    my $opt = $args_ref->[$$index_ref];

    if ($opt eq '-n') {
        $dryrun = 1;
        return 1;

    } elsif ($opt eq '--recursive') {
        $recursive = 1;
        return 1;

    } elsif ($opt eq '--type') {
        $$index_ref++;
        my $t = $args_ref->[$$index_ref];
        defined $t or die "Option --type requires a value (f or d)\n" . usage();
        ($t eq 'f' || $t eq 'd') or die "Invalid --type value '$t' (expected f or d)\n" . usage();
        $ignore_type = $t;
        return 1;

    } elsif ($opt =~ /^--type=(.+)$/) {
        my $t = $1;
        ($t eq 'f' || $t eq 'd') or die "Invalid --type value '$t' (expected f or d)\n" . usage();
        $ignore_type = $t;
        return 1;

    } elsif ($opt eq '--allow-hidden') {
        $allow_hidden = 1;
        return 1;

    } elsif ($opt eq '--allow-dash') {
        $allow_dash = 1;
        return 1;

    } elsif ($opt eq '--allow-ext') {
        $allow_ext = 1;
        return 1;

    } elsif ($opt eq '--preserve-ext') {
        $preserve_ext = 1;
        return 1;
    }

    return 0;
}

sub split_ext {
    my ($f) = @_;
    # last-dot extension only; ext includes the dot, or '' if none
    return ($1, ".$2") if $f =~ /^(.*)\.([^\/.]+)$/;
    return ($f, '');
}

sub has_capture_group {
    my ($pat) = @_;
    # Heuristic: unescaped "(" not followed by ?: ?= ?! ?<
    return $pat =~ /(?<!\\)\((?!\?[:=!<])/;
}

sub looks_like_expr {
    my ($expr) = @_;
    return defined $expr && ($expr =~ /^(?:s|tr|y)\b/ || $expr =~ /^(?:s|tr|y)\W/);
}

sub resolve_expr {
    my ($expr) = @_;

    return 's/_/ /g' if defined $expr && $expr eq '__underscore';
    return $expr;
}

sub validate_expr {
    my ($expr) = @_;

    if (!looks_like_expr($expr)) {
        die "Bad expr: '$expr'\n".
            "It doesn't look like a Perl rename expression (s///, tr///, y///).\n".
            "You probably forgot to quote the expr, or omitted it.\n".
            "Example: rename 's/(S\\d{2}E\\d{2})\\./\\$1 - /' -- *\n";
    }

    if ($expr =~ /^s(.)(.*?)\1(.*?)\1([a-z]*)$/i) {
        my ($delim, $pat, $rep, $mods) = ($1, $2, $3, $4);

        if ($mods =~ /g/ && $pat eq '.') {
            die "Refusing expression '$expr' ... global dot matches can erase filenames\n";
        }
    }

    if ($expr =~ /^s(.)(.*?)\1(.*?)\1([a-z]*)$/i) {
        my ($delim, $pat, $rep, $mods) = ($1, $2, $3, $4);

        my $num_caps = () = ($pat =~ /(?<!\\)\((?!\?[:=!<])/g);  # naive count of capturing parens
        if ($num_caps > 0 && $rep !~ /\$(?:\d+|\{?\w+\}?)/) {
            die "Expression looks like it uses captures, but replacement has no \$1/\$2/... .\n".
                "If you used double quotes, the shell may have expanded them. Use single quotes.\n";
        }
    }

    if ($expr =~ /^s(.)(.*?)\1(.*?)\1([a-z]*)$/i) {
        my ($pat, $rep, $mods) = ($2, $3, $4);

        if (has_capture_group($pat) && $rep !~ /\$/ && $rep =~ /^[\s\-\._]*$/) {
            die "Refusing '$expr' ... replacement has no \$1 etc; likely shell-expanded.\n";
        }
    }
}

my @ops;
my @files;
my $saw_double_dash = 0;

for (my $i = 0; $i < @ARGV; $i++) {
    my $arg = $ARGV[$i];

    if ($arg eq '--') {
        @files = @ARGV[$i + 1 .. $#ARGV];
        $saw_double_dash = 1;
        last;
    }

    if ($arg =~ /^-/ && parse_option(\@ARGV, \$i)) {
        next;
    }

    push @ops, resolve_expr($arg);
}

if (!$saw_double_dash) {
    @ops = ();
    @files = ();
    my @fallback_argv = @raw_argv;

    while (@fallback_argv && $fallback_argv[0] =~ /^-/) {
        my $idx = 0;
        my $handled = parse_option(\@fallback_argv, \$idx);
        $handled or die "Unknown option: $fallback_argv[0]\n" . usage();
        splice @fallback_argv, 0, $idx + 1;
    }

    while (@fallback_argv && looks_like_expr($fallback_argv[0])) {
        push @ops, resolve_expr(shift @fallback_argv);
    }

    @files = @fallback_argv;
}

@ops or die usage();

if ($allow_ext && $preserve_ext) {
    die "Options --allow-ext and --preserve-ext are mutually exclusive\n" . usage();
}

validate_expr($_) for @ops;

@ARGV = @files;

sub file_ext {
    my ($f) = @_;
    return '' if $f !~ /\.([^\/.]+)$/;   # no extension
    return $1;
}

# If no file args remain, read from STDIN
chomp(@ARGV = <STDIN>) unless @ARGV;

sub path_depth {
    my ($p) = @_;
    return () = $p =~ m{/}g;
}

sub split_parent_base {
    my ($p) = @_;
    my $i = rindex($p, '/');
    return ('', $p) if $i < 0;
    return (substr($p, 0, $i + 1), substr($p, $i + 1));
}

if ($recursive) {
    my @expanded;
    my %seen;

    for my $path (@ARGV) {
        if (-d $path) {
            File::Find::find(
                {
                    no_chdir => 1,
                    wanted   => sub {
                        my $name = $File::Find::name;
                        return if $seen{$name}++;
                        push @expanded, $name;
                    },
                },
                $path
            );
            next;
        }

        next if $seen{$path}++;
        push @expanded, $path;
    }

    # Rename deeper paths first so children are handled before parent dirs.
    @ARGV = sort {
        path_depth($b) <=> path_depth($a)
            || $a cmp $b
    } @expanded;
}

# put these once, outside the loop (top-level)
my $RED   = -t STDERR ? "\e[31m" : "";
my $RESET = -t STDERR ? "\e[0m"  : "";

sub skip_red {
    my ($msg) = @_;
    warn "${RED}SKIP: $msg${RESET}\n";
}

for (@ARGV) {
    my $was = $_;

    next if $ignore_type eq 'f' && -f $was;
    next if $ignore_type eq 'd' && -d $was;

    my ($prefix, $base) = split_parent_base($was);
    $_ = $base;

    for my $op (@ops) {
        eval $op;
        die $@ if $@;
    }

    my $new_name = "${prefix}$_";
    next if $was eq $new_name;   # no change

    my $new_component = $_;

    # Disallow leading dash
    if (!$allow_dash && $new_component =~ /^-/) {
        skip_red("'$new_name' begins with '-' (use --allow-dash)");
        next;
    }

    # Disallow hidden
    if (!$allow_hidden && $new_component =~ /^\./) {
        skip_red("'$new_name' is hidden (use --allow-hidden)");
        next;
    }

    # Extension protection (files only)
    if (!$allow_ext && !-d $was) {
        my ($old_stem, $old_ext) = split_ext($was);
        my ($new_stem, $new_ext) = split_ext($new_name);

        if ($old_ext ne $new_ext) {

            if ($preserve_ext && $old_ext ne '') {
                my $candidate = $new_name;
                $candidate =~ s/\.+$//;       # avoid trailing dots
                $candidate =~ s/\.[^\/.]+$//; # strip any last-dot extension
                $candidate .= $old_ext;       # restore original ext (includes '.')

                my (undef, $candidate_component) = split_parent_base($candidate);

                # re-check constraints on candidate
                if (!$allow_dash && $candidate_component =~ /^-/) {
                    skip_red("'$candidate' begins with '-' (use --allow-dash)");
                    next;
                }
                if (!$allow_hidden && $candidate_component =~ /^\./) {
                    skip_red("'$candidate' is hidden (use --allow-hidden)");
                    next;
                }

                if (-e $candidate) {
                    skip_red("'$candidate' already exists, not renaming '$was'");
                    next;
                }

                $new_name = $candidate;

            } else {
                skip_red("extension change '$was' -> '$new_name' (use --allow-ext, or --preserve-ext)");
                next;
            }
        }
    }

    if (-e $new_name) {
        skip_red("'$new_name' already exists, not renaming '$was'");
        next;
    }

    if ($dryrun) {
        print "$was -> $new_name\n";
    } else {
        rename($was, $new_name) or warn "${RED}ERROR: rename('$was','$new_name') failed: $!${RESET}\n";
    }
}
